# Generated by Django 5.0.6 on 2024-06-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("version", models.CharField(max_length=10)),
                (
                    "uid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=10)),
                ("web_sales", models.URLField(blank=True)),
                ("source_web_promote", models.URLField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("hit_rate", models.IntegerField()),
                ("source_web_name", models.CharField(max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("edit_modify_date", models.DateTimeField(blank=True)),
                ("show_unit", models.CharField(blank=True, max_length=100)),
                ("discount_info", models.TextField(blank=True)),
                ("descriptionFilterHtml", models.TextField(blank=True)),
                ("imageUrl", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MasterUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("masterunit_name", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masterunits",
                        to="operation.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("other_unit_name", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_units",
                        to="operation.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("location_name", models.CharField(max_length=255)),
                ("on_sales", models.CharField(max_length=1)),
                ("price", models.CharField(max_length=50)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("end_time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_info",
                        to="operation.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subunit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subunit_name", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subunits",
                        to="operation.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supportunit_name", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supportunits",
                        to="operation.event",
                    ),
                ),
            ],
        ),
    ]
