# Generated by Django 5.0.6 on 2024-06-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="masterunit",
            old_name="masterunit_name",
            new_name="unit_name",
        ),
        migrations.RenameField(
            model_name="otherunit",
            old_name="other_unit_name",
            new_name="unit_name",
        ),
        migrations.RenameField(
            model_name="subunit",
            old_name="subunit_name",
            new_name="unit_name",
        ),
        migrations.RenameField(
            model_name="supportunit",
            old_name="supportunit_name",
            new_name="unit_name",
        ),
    ]
