# Generated by Django 5.0.6 on 2024-06-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation", "0002_rename_masterunit_name_masterunit_unit_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="edit_modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
